defaults:
  - _self_

_target_: src.logger.WandBLogger
group: ${dataset.dataset_name} # Name of the group for wandb
name: ${model.name}_seed=${seed} # Name of the run for wandb
job_type: test
entity: yerenkl-danmarks-tekniske-universitet-dtu
project_name: satellite-road-detection-project
disable: false
local_dir: ./logs #Directory to save logs