defaults:
  - _self_

name: "deepglobe"

init:
  _target_: src.data.create_data
  kaggle_dataset: "balraj98/deepglobe-road-extraction-dataset"
  file_path: "data/deepglobe"
  transforms:
    train:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchvision.transforms.v2.Resize
          size: [256, 256]
        - _target_: torchvision.transforms.v2.RandomHorizontalFlip
          p: 0.5
    val:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchvision.transforms.v2.Resize
          size: [256, 256]
    test:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchvision.transforms.v2.Resize
          size: [256, 256]
  image_column: "sat_image_path"
  mask_column: "mask_path"