defaults:
  - _self_

name: "massasschussetts-roads"

init:
  _target_: src.datasets.data_massachusetts.create_data
  file_path: "data/massasschussetts-roads"
  transforms:
    train:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchvision.transforms.v2.Resize
          size: [256, 256]
        - _target_: torchvision.transforms.v2.RandomHorizontalFlip
          p: 0.5
    val:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchvision.transforms.v2.Resize
          size: [256, 256]
    test:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchvision.transforms.v2.Resize
          size: [256, 256]

  image_column: "tiff_image_path"
  mask_column: "tif_label_path"